modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_authors}"
    description='''${mod_description}'''
    issueTrackerURL="https://github.com/pedroksl/AdvancedAE/issues"
    displayURL="https://github.com/pedroksl/AdvancedAE"
    credits="Ridanisaurus Rid for texture style, JmÂ³ and Sea_Kerman for models"
    logoFile="logo.png"

[[mixins]]
    config="mixins.aae.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="ae2"
type="required"
versionRange="[19.0.26,)"
ordering="AFTER"
side="BOTH"
[[dependencies.${mod_id}]]
modId="glodium"
type="required"
versionRange="[1.21-2.0-neoforge,)"
ordering="AFTER"
side="BOTH"
[[dependencies.${mod_id}]]
modId="geckolib"
type="required"
versionRange="[${geckolib_version},)"
ordering="AFTER"
side="BOTH"